# Generated by Django 4.2 on 2025-08-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='date',
            field=models.DateTimeField(auto_created=''),
        ),
    ]
