# Generated by Django 4.2 on 2025-08-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_watchlist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
