# Generated by Django 4.2 on 2025-08-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_watchlist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
