# Generated by Django 4.2 on 2025-08-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_history_delete_histoy'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_table',
            name='Movie_video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='movie_table',
            name='Movie_thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
